// <auto-generated />
using Lawyers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LA.Services.API.Migrations.LawyerDb
{
    [DbContext(typeof(LawyerDbContext))]
    partial class LawyerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LA.Services.API.Models.LawyerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExpYears")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LawyerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Luật sư chuyên dân sự, hơn 10 năm kinh nghiệm.",
                            DayOfWeek = "Mon,Tue,Wed",
                            Description = "Hà Nội",
                            ExpYears = 10,
                            Img = "lawyer1.jpg",
                            LicenseNum = "LS1234",
                            PricePerHour = 500000.0,
                            Rating = 4.9000000000000004,
                            Spec = "Dân sự,Hợp đồng",
                            UserId = 1,
                            WorkTime = "08:00-12:00"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Luật sư hình sự, tư vấn luật hơn 8 năm.",
                            DayOfWeek = "Thu,Fri",
                            Description = "TP. HCM",
                            ExpYears = 8,
                            Img = "lawyer2.jpg",
                            LicenseNum = "LS5678",
                            PricePerHour = 600000.0,
                            Rating = 4.7000000000000002,
                            Spec = "Hình sự,Tố tụng",
                            UserId = 2,
                            WorkTime = "13:00-17:00"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Luật sư chuyên về đất đai và bất động sản.",
                            DayOfWeek = "Mon,Wed,Fri",
                            Description = "Đà Nẵng",
                            ExpYears = 12,
                            Img = "lawyer3.jpg",
                            LicenseNum = "LS9001",
                            PricePerHour = 700000.0,
                            Rating = 4.7999999999999998,
                            Spec = "Đất đai,Bất động sản",
                            UserId = 3,
                            WorkTime = "09:00-11:00"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Luật sư trẻ đầy nhiệt huyết, chuyên luật doanh nghiệp.",
                            DayOfWeek = "Tue,Thu",
                            Description = "Hải Phòng",
                            ExpYears = 5,
                            Img = "lawyer4.jpg",
                            LicenseNum = "LS7004",
                            PricePerHour = 400000.0,
                            Rating = 4.5999999999999996,
                            Spec = "Doanh nghiệp,Hợp đồng",
                            UserId = 4,
                            WorkTime = "14:00-17:00"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Luật sư có chuyên môn sâu về hôn nhân gia đình.",
                            DayOfWeek = "Sat,Sun",
                            Description = "Cần Thơ",
                            ExpYears = 7,
                            Img = "lawyer5.jpg",
                            LicenseNum = "LS3010",
                            PricePerHour = 450000.0,
                            Rating = 4.8499999999999996,
                            Spec = "Hôn nhân,Ly hôn,Nuôi con",
                            UserId = 5,
                            WorkTime = "08:00-12:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
